name: docker-compose-actions-workflow
on:
  push:
    branches: [ v0.1 ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando Applicacao - src/
        run: git clone https://github.com/rop-e/application.git src
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d --build --force-recreate
      - name: Espere eu me recompor
        uses: juliangruber/sleep-action@v1
        with:
          time: '10s' 
      - name: Show contianers
        run: docker-compose ps
      - name: Run migrate
        run: docker-compose exec -T webapp python manage.py migrate
      - name: Create a admin User
        run: docker-compose exec -T webapp python manage.py makesuper 
      - name: Run test
        run: docker-compose exec -T webapp python manage.py test  
